### ISSUE TITLE
Move core components for `common_resources` to this repo

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/core#4]

**Comment by KaiWaldrant** [comment]
add common compontents to core repo.

* build on viash hub
* make executable fro openproblems task to use

**Comment by KaiWaldrant** [comment]
During the preparation for this issue I came to a thought that we need to discuss.

The components use helper_functions in the common_resources repo atm (not yet in the core pacakges). But it also uses the `openproblems` pakcages in this repo. isn't this going to cause some sort of conflict ?
